### ISSUE TITLE
Base fish prompt color on vi mode

### ISSUE THREAD

**Issue by rahuldhir** [cqsd/dotfiles#3]
https://github.com/cqsd/dotfiles/blob/8b1f64cc575a76b84b7da8942def4e8c88d1ece1/base.fish#L16-L18

Take a look at:
https://github.com/rahuldhir/dotfiles/blob/007a5e48ac48b1800ad21a0206d0a4e9dc4c637e/.config/fish/functions/fish_prompt.fish#L14-L30

**Comment by cqsd** [comment]
ah thx, changed in https://github.com/cqsd/dotfiles/commit/25be5716b1429d7411c5e8e47b710a19d19daac3

**Comment by rahuldhir** [comment]
np

**Comment by cqsd** [comment]
love too collarborate on Open Source Software

**Comment by rahuldhir** [comment]
!

**Comment by jacct** [comment]
WOW! A great initiative from my mentee @rahuldhir. Keep up the good work! 🥇
